# Generated by Django 5.1.3 on 2024-11-27 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('count', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Остаток на складе')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['title'], name='api_book_title_dc9757_idx'), models.Index(fields=['author'], name='api_book_author__b1bddf_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'author'), name='unique_for_author_book')],
            },
        ),
    ]
