# Generated by Django 5.1.3 on 2024-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_for_book',
        ),
    ]
